services:
  - type: web
    name: ayursetu-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: EMAILJS_SERVICE_ID
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        sync: false
      - key: EMAILJS_PRIVATE_KEY
        sync: false
      - key: EMAILJS_ACCEPTANCE_TEMPLATE
        sync: false
      - key: EMAILJS_REMINDER_TEMPLATE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
